version: '3'

services:
  ecomm-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Ajustez le port si nécessaire
      - "8010:80"  # Ajustez le port si nécessaire
    volumes:
      - /c/Users/najar/Desktop/ecomm-application:/app
    environment:
      - NODE_ENV=development
