version: '3'
services:
  ecomm-angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecomm-angular
    container_name: ecomm-angular
    volumes:
      - ./:/home/
    environment:
      - MONGO_USERNAME=mongo
      - MONGO_PASSWORD=mongo
      - MONGO_PORT=27017

    ports:
      - 8080:80
